class ParamsTable(list):

    def __init__(self):
        self.append({'name': 'PS Name',                 'value': []})
        self.append({'name': 'PS Model',                'value': []})
        self.append({'name': 'PS Modules',              'value': []})
        self.append({'name': 'Command Interface',       'value': []})
        self.append({'name': 'RS485 Baudrate',          'value': []})
        self.append({'name': 'RS485 Address',           'value': []})
        self.append({'name': 'RS-485 Termination',      'value': []})
        self.append({'name': 'UDC Network Address',     'value': []})
        self.append({'name': 'Ethernet IP',             'value': []})
        self.append({'name': 'Ethernet Subnet Mask',    'value': []})
        self.append({'name': 'Freq Control ISR',        'value': []})
        self.append({'name': 'Freq TimeSlicer',         'value': []})
        self.append({'name': 'Control Max Ref',         'value': []})
        self.append({'name': 'Control Min Ref',         'value': []})
        self.append({'name': 'Max Ref Open-Loop',       'value': []})
        self.append({'name': 'Min Ref Open-Loop',       'value': []})
        self.append({'name': 'Slew-Rate SlowRef',       'value': []})
        self.append({'name': 'Slew-Rate Siggen Amp',    'value': []})
        self.append({'name': 'Slew-Rate Siggen Offset', 'value': []})
        self.append({'name': 'Slew-Rate Siggen WfmRef', 'value': []})
        self.append({'name': 'Freq PWM',                'value': []})
        self.append({'name': 'Dead Time',               'value': []})
        self.append({'name': 'Max Duty Cycle',          'value': []})
        self.append({'name': 'Min Duty Cycle',          'value': []})
        self.append({'name': 'Max Duty Open-Loop',      'value': []})
        self.append({'name': 'Min Duty Open-Loop',      'value': []})
        self.append({'name': 'Lim. Duty Share',         'value': []})
        self.append({'name': 'Num Boards HRADC',        'value': []})
        self.append({'name': 'SPI Clk',                 'value': []})
        self.append({'name': 'Freq Sampling',           'value': []})
        self.append({'name': 'Enable Heater',           'value': []})
        self.append({'name': 'Enable Rails Monitor',    'value': []})
        self.append({'name': 'Transducer Output',       'value': []})
        self.append({'name': 'Transducer Gain',         'value': []})
        self.append({'name': 'Transducer Offset',       'value': []})
        self.append({'name': 'Siggen Type',             'value': []})
        self.append({'name': 'Num Cycles',              'value': []})
        self.append({'name': 'Siggen Freq',             'value': []})
        self.append({'name': 'Siggen Amp',              'value': []})
        self.append({'name': 'Siggen Offset',           'value': []})
        self.append({'name': 'Aux Parameters',          'value': []})
        self.append({'name': 'WfmRef ID',               'value': []})
        self.append({'name': 'Sync Mode',               'value': []})
        self.append({'name': 'WfmRef Gain',             'value': []})
        self.append({'name': 'WfmRef Offset',           'value': []})
        self.append({'name': 'Analog Variables Max',    'value': []})
        self.append({'name': 'Analog Variables Min',    'value': []})
